### ISSUE TITLE
Is it minSDK 21?

### ISSUE THREAD

**Issue by sevar83** [sergiocasero/RevealFAB#1]
Hi, when I tried to build it, gradle complains that RevealFAB library requires minSDK=21 and mine is 15. Is it really intended for 21!? I suppose you've just forgotten to lower `minSdkVersion` in `build.gradle`.

**Comment by sergiocasero** [comment]
Ups, I'm so sorry, I will update it soon as posible!!

**Comment by NikhilAndroidDev** [comment]
It will be helpful if you use AP level 14 as minimum SDK

**Comment by sergiocasero** [comment]
Hello! I promise you that I will update for add support to min 15!!!, but I have no time, sorry guys. Maybe in next week...

**Comment by kaushikb1996** [comment]
I think I can make the changes if you want what do you say ?

**Comment by kaushikb1996** [comment]
I Have made the necessary changes to make the minimum api level to 14 and also complied with the new design libraries. Hope you accept the changes :)

Looking forward for you reply !

**Comment by sergiocasero** [comment]
@kaushikb1996 i will do it now!!! sorry my friends

**Comment by kaushikb1996** [comment]
Thank you :)

**Comment by kaushikb1996** [comment]
And don't forget to close this issue noe after compiling the library !

**Comment by kaushikb1996** [comment]
#2 Hey @sergiocasero please consider closing this is issue once you build the maven lib
